lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'

when@test:
    lexik_jwt_authentication:
        secret_key: '%kernel.project_dir%/config/jwt/test_private.pem'
        public_key: '%kernel.project_dir%/config/jwt/test_public.pem'
        pass_phrase: ''
